### ISSUE TITLE
Download button on file page is hard to spot

### ISSUE THREAD

**Issue by pointyointment** [camsong/chrome-github-mate#19]
I often spend several seconds looking for the button, because it's disguised as a view mode tab. I think it would be much better to fit it into the icon buttons just to the right of its present location.

**Comment by camsong** [comment]
![image](https://cloud.githubusercontent.com/assets/948896/18555295/fa6e4824-7b99-11e6-98cc-ce07ad6fe2c3.png)
Fixed like this
