### ISSUE TITLE
Detect gh-pages

### ISSUE THREAD

**Issue by vohof** [camsong/chrome-github-mate#2]
Sometimes there's a gh-pages branch for a repo but it isn't linked anywhere so one has to type 'username.github.io/repo`.

![](http://i.imgur.com/ahrU4MV.png)

**Comment by camsong** [comment]
I do not have the 'GH Page' button, I guess it's added by some other extensions you installed.
![image](https://cloud.githubusercontent.com/assets/948896/5646570/cd6932e8-96b8-11e4-9d3e-b12638b0acec.png)

**Comment by vohof** [comment]
@camsong Yes, I just modified the html from dev tools. I think it would be something helpful this extension could add.

**Comment by camsong** [comment]
Aha, good idea :clap: let me add this feature

**Comment by camsong** [comment]
Implemented in [v0.8.1](https://github.com/camsong/chrome-github-mate/releases/tag/v0.8.1)

**Comment by vohof** [comment]
:clap:
