### ISSUE TITLE
Uncaught TypeError: $ is not a function

### ISSUE THREAD

**Issue by bfred-it** [camsong/chrome-github-mate#25]
This error appears in the console:

<img width="414" alt="Uncaught TypeError: $ is not a function" src="https://cloud.githubusercontent.com/assets/1402241/17060468/0580e758-4fdf-11e6-8418-ca47060b2bd7.png">

https://github.com/camsong/chrome-github-mate/blob/master/page.js#L1

Version 52.0.2743.82 beta (64-bit)

**Comment by leoj3n** [comment]
I'm seeing the same error 😢
