### ISSUE TITLE
Wide mode doesn't widen graphs/"network view"

### ISSUE THREAD

**Issue by gdevenyi** [camsong/chrome-github-mate#31]
The box around the network view is widened however the actual network isn't.

**Comment by camsong** [comment]
What's the network view, can you make a screenshot?

**Comment by gdevenyi** [comment]
![screenshot from 2016-09-21 10 27 42](https://cloud.githubusercontent.com/assets/3001850/18715106/1331d4d4-7fe6-11e6-964b-e8c36f539dac.png)

Notice the network diagram cuts off in the middle of the (properly widened) box.

**Comment by camsong** [comment]
![image](https://cloud.githubusercontent.com/assets/948896/18735097/bda09712-80ad-11e6-9b16-a3a7d183a458.png)
It works here, chrome-github-mate will not modify styles here. Can you start incognito mode to check if it still break?

**Comment by gdevenyi** [comment]
Oh shit, you don't have a wide mode, that's another extension. Sorry!

P.S. Feature request, wide mode, ref: https://github.com/thecodejunkie/github.expandinizr
