### ISSUE TITLE
[Question] What is the extension / style that changes the layout in the screenshot?

### ISSUE THREAD

**Issue by vladfrangu** [camsong/chrome-github-mate#46]
Hello!

Your extension is amazing! I find it very useful, but I have a question.

In this screenshot, ![](https://camo.githubusercontent.com/7d645ce52709979d2657c653dd06e028af28a89b/68747470733a2f2f6c68332e676f6f676c6575736572636f6e74656e742e636f6d2f6b5445686d657034684d314d6b6e7231494c48674656497a5338612d57737a73644b6a5630714838516a70374d2d726259412d794e522d574136766f575937677447394449426e3755773d733634302d683430302d653336352d7277)
, the right bar is different. i quite like how it looks, so I was wondering if you could tell me how to get it!

Thanks!

**Comment by camsong** [comment]
The right bar is GitHub's previous design, moved to the upper side right now, will update the screenshot later

![image](https://user-images.githubusercontent.com/948896/50440162-e022ca00-092f-11e9-9e13-6c574c622792.png)
