### ISSUE TITLE
Ignore whitespace in diffs automatically

### ISSUE THREAD

**Issue by riophae** [camsong/chrome-github-mate#5]
How about [adding `?w=1` to any diff URLs](https://github.com/tiimgreen/github-cheat-sheet#ignore-whitespace) automatically as optional? Personally speaking it's pretty useful, as I hardly ever care about any changes only in whitespace.

**Comment by camsong** [comment]
Thanks for pointing out such an useful trick :clap: , I'm sure it will help a lot of people.
In order not to confuse people who has got used to the current diff content, maybe we can add a button to enable this magic like this:

![image](https://cloud.githubusercontent.com/assets/948896/7119859/bc0b14ca-e23b-11e4-9556-bb127f869073.png)

 if you got a getter idea, glad to change.

**Comment by camsong** [comment]
A diff which may confuse people with this trick
https://github.com/angular/angular.js/pull/10539/files?w=1

**Comment by riophae** [comment]
Well done! 👍 Blazing fast!
Yes, indeed. In specific cases it would be very confusing.

I just came up with an alternative approach worth considering.
1. A checkbox in option page setting up whether `?w=1` will be added to any diff links automatically. The checkbox is unchecked as default, as users should be clear about the function before it being enabled.
2. Turn on the function manually. (In my opinion,) it would be without any problems in most cases.
3. With this trick, very rarely and unfortunately, the situation that no changes couldn't be shown is possible. And there is not a hint, which causes confusion. Okay. How about appending a hint into the page, leading user to the normal diff page?
4. Even more advanced (and radically), user could be redirected to the page without `?w=1` automatically, then we can show a  hint that why whitespace hiding is disabled.
5. However, automatical redirecting is VERY RISKY. Please avoid of using it as far as possible.

May be a bit opinionated... or just all my fantasy :D
Thx for your patience!

**Comment by mattsfrey** [comment]
Is there any consideration for this still? Having an option to default PR's to not showing whitespace diffs would be extremely useful, especially for those of us writing clojure and aligning maps values, as an example. We get diffs that are often 50% or more just whitespace and have been having to manually append the ?w=1 to our PR URLS.

**Comment by camsong** [comment]
Prepare to add this but does not have time, PR is welcomed.

**Comment by camsong** [comment]
Finally this feature comes out. Will toggle between `Show Spaces` and `Ignore Spaces` like
![image](https://cloud.githubusercontent.com/assets/948896/18557722/af34b358-7ba2-11e6-8203-a572d61f0f0e.png)

![image](https://cloud.githubusercontent.com/assets/948896/18557731/b78fffda-7ba2-11e6-993f-0af3d92ddf2a.png)

**Comment by riophae** [comment]
Seems it's not applied to commit details page? I didn't see a "Ignore Spaces" button there.

**Comment by camsong** [comment]
release v0.16.3 to fix this

**Comment by amit133** [comment]
I am not able to see this feature
![image](https://cloud.githubusercontent.com/assets/10413604/21714003/dad326d8-d422-11e6-9b25-2ebb9e75f720.png)

**Comment by ArtS** [comment]
Is this ever going to be available in Pull Requests?

**Comment by camsong** [comment]
@ArtS @amit133 fixed in v0.16.5

**Comment by tofixx** [comment]
Is it possible to see that button in pull requests too?

**Comment by roboweaver** [comment]
The w=1 trick is nice for viewing diffs, unfortunately you can't add comments for the Pull Request which is where this would be most useful.

Really annoying to not be able to see your actual change in a file that accidentally (or intentionally) got formatted as part of a commit, since changing the whitespace doesn't matter in most languages.

**Comment by meisertedu** [comment]
Are team would get alot of use from the menu/button option for selecting "no spaces" in diff when doing PRs.  One common use-case for us is Jenkins often changes spaces/tabs to files automatically... which then leads to lots of file diff segments that are not "real" diffs.  This button suggestion above would be great in the PR Files Changed tab/section.

**Comment by phicharp** [comment]
Any time estimate for when this will finally make it?
Hopefully ignoring spaces will not ignore **leading** white spaces in python?

**Comment by camsong** [comment]
Better to turn 'Hide Space' off in python code

**Comment by phicharp** [comment]
@camsong : we are moving a rather old project to using autopep8 and many spaces are removed (old style was with spaces after and before parentheses, around "=" etc...) and it is quite painful to see "real changes" if any, so hiding spaces is nice, but of course leading spaces are a problem...

**Comment by camsong** [comment]
@phicharp It's hard to support that. Right now, "hide space" is a feature supported by github, can not be modified.

**Comment by phicharp** [comment]
OK, I understand this is not easy to implement, but AFAIS it is not exposed in the web interface, is it? I manage by adding "by hand" `?w=1` to the URL but this is not really nice

**Comment by ericarnold-granular** [comment]
Just wanted to leave another vote to add a button to PR pages to do this.  I learned of the trick using w=1, but wish there was a way to make that the default.  I agree there are times when it should be flipped off, so having the button at the top of the page would be ideal.  

Any chance of getting this promoted to a user pref setting that is applied automatically as the default state, then having the button to flip from there?

Thanks

**Comment by camsong** [comment]
@ericarnold-granular  Will consider about this

**Comment by glynhudson** [comment]
Agree, this should be default. Or at least a toggle option. Please make it happen 👍

**Comment by nadim** [comment]
I love the checkbox that's been added for Hide Whitespace Changes. Can we add an option to make it the default parameter?

**Comment by nicolas-albert** [comment]
@nadim I search and I didn't find the checkbox on a page with code changes, I have to add w=1 by hand ...
Where can I find it please ?

**Comment by nadim** [comment]
![image](https://user-images.githubusercontent.com/24093/44482775-92efbe00-a606-11e8-9a09-c9f4db7b09cb.png)

**Comment by nicolas-albert** [comment]
@nadim oops, I haven't seen that the report was for a Chrome extension :-Z
I have installed it now 👍 
Thx !

**Comment by nadim** [comment]
What chrome extension?

I'm pretty sure this is default github behaviour. No extension required.

**Comment by nicolas-albert** [comment]
On this kind of page, there is no button by default : 
https://github.com/nicolas-albert/c8o_yaml_projects/commit/bb851e57ae0a242b46bedb5bb25cb95ba3c173db?w=1

I have installed Octo Mate to have the Ignore / Show Spaces button.

**Comment by lekova** [comment]
@nadim do you know if that checkbox selection can be persisted? I find myself selecting it and then the page is reloaded, the selection is gone.

**Comment by mlandisbqs** [comment]
+1 for a persistent toggle - thank you!

**Comment by alamothe** [comment]
Is it supported to persist the setting across PRs?

**Comment by mustafaozhan** [comment]
+1 for persistency, I want it to be saved as my user preference, so I will not have to enable it for each PR I am reviewing

**Comment by YannikBartel** [comment]
+1 for persistent

**Comment by dcumings** [comment]
+1 for persistency.
Found this in the short term:
https://chrome.google.com/webstore/detail/github-whitespace/fnpkdafamnbjoldglihkjjdicofghccm/related?hl=en-US
