### ISSUE TITLE
Project Dead?? - Need a maintainer?

### ISSUE THREAD

**Issue by gareth-johnstone** [camsong/chrome-github-mate#52]
Assuming this project is dead since its not been maintained for quite some time (and there is no chrome extension in the store anymore?)

Are you looking for someone to maintain it?

I have some ideas  - was planning on forking it for myself - but I'd be happy to take this over?

**Comment by camsong** [comment]
@gareth-johnstone we can talk via gmail neosoyn@gmail.com
