### ISSUE TITLE
Add option to only show notifications count for participating issues

### ISSUE THREAD

**Issue by Anahkiasen** [camsong/chrome-github-mate#9]
Would be nice if there was an option to display the number of notifications I'm participating in instead of the global count, which I'm not necessarily interested in

**Comment by camsong** [comment]
Yep, this should be cool. Let me find out how to implement this.

**Comment by camsong** [comment]
added in v0.10.0
![image](https://cloud.githubusercontent.com/assets/948896/10140109/9c7a5946-6638-11e5-993a-0e4c0af6e4ba.png)
